# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "afe564c9cd07a3dc2d4bfa7229649ac7"
application_url = "https://begin-opinion-contests-austria.trycloudflare.com"
embedded = true
name = "wishlist"
handle = "wishlist-498"

[webhooks]
api_version = "2025-01"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://begin-opinion-contests-austria.trycloudflare.com/auth/callback",
  "https://begin-opinion-contests-austria.trycloudflare.com/auth/shopify/callback",
  "https://begin-opinion-contests-austria.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false

[build]
dev_store_url = "skibididev.myshopify.com"
automatically_update_urls_on_dev = true
include_config_on_deploy = true
